//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDP.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExportLat
    {
        public int ELId { get; set; }
        public System.DateTime ELDate { get; set; }
        public string ELName { get; set; }
        public string ELSize { get; set; }
        public int ELCount { get; set; }
        public double ELPMass { get; set; }
        public double ELKMass { get; set; }
        public double ELKMassBrutto { get; set; }
    
        public virtual Detail Detail { get; set; }
    }
}
