//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDP.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Forging
    {
        public int FId { get; set; }
        public System.DateTime FDate { get; set; }
        public string FName { get; set; }
        public string FSize { get; set; }
        public double FMass { get; set; }
    
        public virtual Detail Detail { get; set; }
    }
}
