//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDP.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sharping
    {
        public int SId { get; set; }
        public System.DateTime SDate { get; set; }
        public string SName { get; set; }
        public string SSize { get; set; }
        public double SMass { get; set; }
    
        public virtual Detail Detail { get; set; }
    }
}
